package models;

import annotations.*;

public class Venue {

    @GreaterThan(0)
    @Unique
    @AutoGenerated
    private long id;

    @NonNull
    @NonEmpty
    private String name;

    @GreaterThan(0)
    private Integer capacity;

    private VenueType type; //Поле может быть null
    private Address address; //Поле может быть null

    public Venue (long id, String name, Integer capacity, VenueType type, Address address){
        this. id = id;
        this.name = name;
        this.capacity = capacity;
        this.type = type;
        this.address = address;
    }

    public long getId(){
        return id;
    }

    @Override
    public String toString() {
        return "Venue{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", capacity=" + capacity +
                ", type=" + type +
                ", address=" + address +
                '}';
    }
}
